spring.application.name=projeto-integrador-web-app

# config perfil de teste
spring.profiles.active=prod

spring.jpa.open-in-view=true

logging.level.org.springframework.security=DEBUG

logging.level.org.springframework.web=DEBUG