# config db
spring.datasource.url=${DOCKER_DATABASE_URL}
spring.datasource.username=${DOCKER_DATABASE_USER}
spring.datasource.password=${DOCKER_DATABASE_PASSWORD}

# JPA, SQL
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true