CREATE TABLE IF NOT EXISTS public.tb_category (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(255)
);


--
-- Name: tb_order; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.tb_order (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    moment timestamp(6) with time zone,
    order_status character varying(255),
    total double precision NOT NULL,
    client_id bigint,
    CONSTRAINT tb_order_order_status_check CHECK (((order_status)::text = ANY ((ARRAY['AGUARDANDO_PAGAMENTO'::character varying, 'PROCESSANDO_PAGAMENTO'::character varying, 'PAGO'::character varying, 'CANCELADO'::character varying])::text[]))),
    CONSTRAINT fk_order_client FOREIGN KEY (client_id) REFERENCES public.tb_user(id)
);


--
-- Name: tb_order_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.tb_order_item (
    preco double precision NOT NULL,
    quantidade integer,
    subtotal double precision NOT NULL,
    product_id bigint NOT NULL,
    order_id bigint NOT NULL,
    PRIMARY KEY (order_id, product_id),
    CONSTRAINT fk_order_item_product FOREIGN KEY (product_id) REFERENCES public.tb_product(id),
    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES public.tb_order(id)
);


--
-- Name: tb_payment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.tb_payment (
    moment timestamp(6) with time zone,
    status character varying(255),
    order_id bigint NOT NULL PRIMARY KEY,
    CONSTRAINT tb_payment_status_check CHECK (((status)::text = ANY ((ARRAY['PENDENTE'::character varying, 'PAGO'::character varying, 'CANCELADO'::character varying])::text[]))),
    CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES public.tb_order(id)
);


--
-- Name: tb_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.tb_product (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    descricao character varying(255),
    img_url character varying(255),
    nome character varying(255),
    preco double precision NOT NULL
);


--
-- Name: tb_product_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.tb_product_category (
    product_id bigint NOT NULL,
    category_id bigint NOT NULL,
    PRIMARY KEY (product_id, category_id),
    CONSTRAINT fk_product_category_product FOREIGN KEY (product_id) REFERENCES public.tb_product(id),
    CONSTRAINT fk_product_category_category FOREIGN KEY (category_id) REFERENCES public.tb_category(id)
);


--
-- Name: tb_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.tb_user (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email character varying(255),
    login character varying(255),
    nome character varying(255),
    role character varying(255),
    senha character varying(255),
    telefone character varying(255),
    CONSTRAINT tb_user_role_check CHECK (((role)::text = ANY ((ARRAY['ROLE_ADMIN'::character varying, 'ROLE_USER'::character varying])::text[])))
);